source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

target 'XZDataLayerViewerSampleApp' do
  pod 'XZDataLayerViewer', :path => '../'

#  target 'aaabbb_Tests' do
#    inherit! :search_paths
#  end
end
